databases:
  - name: mashalifshin
    databaseName: mashalifshin_production
    user: mashalifshin
    ipAllowList:
      - source: 23.93.74.28
        description: home office

services:
  - type: web
    name: mashalifshin
    runtime: ruby
    numInstances: 3
    branch: main
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/render-pre-deploy.sh"
    startCommand: bundle exec rails server
    maxShutdownDelaySeconds: 120
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mashalifshin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
