FOG_DIRECTORY: 'mashalifshin'
AWS_ACCESS_KEY_ID: 'AKIAJJYLJYJZKWVHN2XA'
AWS_SECRET_ACCESS_KEY: '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'
CLOUDFRONT_DISTRIBUTION_DOMAIN: 'http://d2m073ezu2137w.cloudfront.net'